### ISSUE TITLE
Version Number and Build date show n/a

### ISSUE THREAD

**Issue by shibu2006** [chewiebug/GCViewer#119]
In Help -> About GCViewer windows both Version and Build date is shown as n/a.

**Comment by shibu2006** [comment]
Okay what I saw in my case is that I have but JDK and JRE installed and when I see the version of both these with exact path as you said I found the JRE to be with the version details as follows 

java version "1.7.0_40"
Java(TM) SE Runtime Environment (build 1.7.0_40-b43)
Java HotSpot(TM) 64-Bit Server VM (build 24.0-b56, mixed mode)

Where as JDK version is as follows

java version "1.7.0_03"
Java(TM) SE Runtime Environment (build 1.7.0_03-b05)
Java HotSpot(TM) 64-Bit Server VM (build 22.1-b02, mixed mode)

Hence in case I try with the approach you suggested with JDK it shows both version and build details in GCViewer but not with the JRE.

Hope I am clear. In case not please feel free to question me.

Thanks
Shibu

**Comment by ecki** [comment]
Hm strange, it works for me with JRE as wenn as 7u40. No idea what is going on. The only change I would do is to use the class loader of the BuildInfoReader class itself instead of the TCCL:

https://github.com/chewiebug/GCViewer/blob/master/src/main/java/com/tagtraum/perf/gcviewer/util/BuildInfoReader.java#L28

**Comment by chewiebug** [comment]
Hi ecki

Thanks for tracking down this issue! I also can't find a reason, why jre7u3 shouldn't be able to load the build information.

I usually use the contextClassLoader of the current thread, because I once learned, that in multithreaded (Java EE) environments it is the right thing to do. Is it just a hunch, that you propose to use the classes own classloader?

**Comment by ecki** [comment]
I try to stay away from the TCCL as it can be set to different things in different environments. And especially in cases where I know I want to load a resource from a specific JAR it is my habit to use the loader from one class. 

Thinking about it, I know there are some alternative launchers which forget to set the TCCL to the app class loader for the main thread. Maybe that is somewhat related to the problem. We could add a fallback to the class' class loader if the TCCL does not find the resource.I guess I will produce a small test-app to debug @shibu2006 system as I am very curious what is going on.

**Comment by chewiebug** [comment]
It looks like, I'll have to read a bit more about TCCL. If you find out 
the real problem behind this issue, it would definitely be interesting.

**Comment by ecki** [comment]
I think the problem is, that the application classloader does merge multiple JARs. When you start it with -jar there is normally only one, but as it seems there might be cases where this is not the case. We would need to iterate all manifest-resources (getResources("/META-INF/MANIFEST.MF") and find the right one, or if we can limit us to Specification-Version, it would be `getClass().getPackage().getImplementationVersion()`. If we add the build timestamp to Implementation-Version (but not Specification-Version) I think this would be enough.
