### ISSUE TITLE
Question - Plot with multiple "VM Operations Events"

### ISSUE THREAD

**Issue by dav009** [chewiebug/GCViewer#159]
A bit of Spam, but got confused while taking a look at stats generated by GCViewer.

Im seeing lots of  red GC Times Rectangles (which stand for : "vm operation event ("application stopped...")"

I wonder:
 -  GCviewer-wise these red rectangles means  a stopworld operation occurred and it was not a GC Stop ?

- The statistics in : `Total Pause` do not correspond to the sum of `Full GC stop` + `GC Pauses` so it means the stops came from events different from GC?

- Completely unrelated but is there a way to know what were those events (is there any JVM flag?)

![screen shot 2016-01-14 at 12 09 36](https://cloud.githubusercontent.com/assets/1659415/12324120/6bd7cf74-bab8-11e5-8647-82e86e084bf1.png)

**Comment by chewiebug** [comment]
Hi,

These red rectangles are picked up from the gc log, when the following 
lines are found:

"Total time for which application threads were stopped: 0.0286830 seconds"

These are always stop the world events, but may not only be caused by 
garbace collection events: see 
http://blog.ragozin.info/2012/10/safepoints-in-hotspot-jvm.html

What you see in GCViewer as the red rectangles is only the "overhead" 
created by these log statements. Here is an example:
2012-04-26T23:59:51.591+0400: 33395.846: [GC 33395.846: [ParNew: 
130944K->0K(131008K), 0.0270510 secs] 1080878K->958238K(4194240K), 
0.0272180 secs] [Times: user=0.16 sys=0.00, real=0.03 secs]
Total time for which application threads were stopped: 0.0286830 seconds

GCViewer records 0.0270510s for the GC, ParNew event and additional 
0.001465s for the "application stopped" event (as overhead over the gc 
event). If the "application stopped" event is not preceded by a GC 
event, the full pause time is counted for "application stopped".

So, to answer your questions:

 1. the red rectangles may contain a gc pause, but they don't always do so
      * No, "Total pause" includes "gc pauses" + "full gc pauses" + "vm
        operations overhead" (you can see the percentage of each in the
        "event details" tab behind the chart
 2. I think, the second question is mostly answered by my explanations
    above. The corresponding flag is -XX:+PrintGCApplicationStoppedTime


In your case, it looks like you have a problem outside the garbace 
collection events, that takes a lot more time than the gc events 
themselves. Thread contention might be a reason, but I think, there are 
other possible reasons. If you need help in analysing your situation, 
then an email to hotspot-gc-use@openjdk.java.net 
<mailto:hotspot-gc-use@openjdk.java.net> is a good way to start. There 
are quite a few experts around.

Best regards,
Jörg

**Comment by dav009** [comment]
thanks for the clear answer :+1:
