### ISSUE TITLE
java.io.IOException: Failed to recognize file format. Failed to recognize file format

### ISSUE THREAD

**Issue by shishir127** [chewiebug/GCViewer#179]
I'm not able to figure out why I get this exception. I ran my app with these flags
`CommandLine flags: -XX:InitialHeapSize=246412032 -XX:MaxHeapSize=3942592512 -XX:+PrintGC -XX:+PrintGCCause -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+UseCompressedClassPointers -XX:+UseCompressedOops -XX:+UseParallelGC`

Please pardon me if this is not an issue with GCViewer, I'm trying to tinker with the JVM and I don't fully understand why this log is invalid. I've also attached the log
[gc.log.zip](https://github.com/chewiebug/GCViewer/files/470013/gc.log.zip)

**Comment by chewiebug** [comment]
Hi

The problem GCViewer has with your logfile is, that it contains no events to parse, at all. It just contains the "introduction":

```
Java HotSpot(TM) 64-Bit Server VM (25.101-b13) for linux-amd64 JRE (1.8.0_101-b13), built on Jun 22 2016 02:59:44 by "java_re" with gcc 4.3.0 20080428 (Red Hat 4.3.0-8)
Memory: 4k page, physical 15400752k(10536892k free), swap 0k(0k free)
CommandLine flags: -XX:InitialHeapSize=246412032 -XX:MaxHeapSize=3942592512 -XX:+PrintGC -XX:+PrintGCTimeStamps -XX:+UseCompressedClassPointers -XX:+UseCompressedOops -XX:+UseParallelGC
```

As soon as there is more content, GCViewer should be able to show something.

The log in itself looks valid.

Best regards,
Jörg

PS: I'll close this issue, since I believe, you will get along without further help.
