### ISSUE TITLE
Automatically set start time

### ISSUE THREAD

**Issue by gysel** [chewiebug/GCViewer#184]
I've got an idea for a new feature: When opening a log that was generated with `-XX:+PrintGCTimeStamps`, the start time could be set automatically. This would save the user a couple of clicks.

**Comment by chewiebug** [comment]
Hi Michi

Currently (latest 1.35-SNAPSHOT version), GCViewer can either show the 
time since start of the VM or the absolute dates. Switching between the 
two modes can be done using the view menu -> "show datestamps" or 
directly doing a rightclick on the time scale.

If a log with -XX:+PrintGCTimeStamps is switched to "show datestamps", 
the date proposed for the beginning of the log is the modification 
timestamp of the log file. The last state chosen for "show datestamps" 
will be used after the next startup of GCViewer.

Does this functionality already cover your idea or is there something 
missing?

Best regards
Jörg

**Comment by gysel** [comment]
Hi Jörg

> Currently (latest 1.35-SNAPSHOT version), GCViewer can either show the
> time since start of the VM or the absolute dates. Switching between the
> two modes can be done using the view menu -> "show datestamps" or
> directly doing a rightclick on the time scale.

I was not aware of this! Great! This makes my suggestion obsolete. I only recently switched my local version of the GCViewer to the develop branch.

Regards
Michi

**Comment by chewiebug** [comment]
Hi Michi

Good to hear! I should probably do something about my release strategy - 
they should not be that rare an occurence.

Regards,
Jörg
